//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinevoScraper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class CinevoScraper : global::System.Configuration.ApplicationSettingsBase {
        
        private static CinevoScraper defaultInstance = ((CinevoScraper)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CinevoScraper())));
        
        public static CinevoScraper Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CleanDirectories {
            get {
                return ((bool)(this["CleanDirectories"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\HtmlFiles\\Cinemas\\")]
        public string Cinemas {
            get {
                return ((string)(this["Cinemas"]));
            }
            set {
                this["Cinemas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\HtmlFiles\\Films\\")]
        public string Film {
            get {
                return ((string)(this["Film"]));
            }
            set {
                this["Film"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string ForceRequest {
            get {
                return ((string)(this["ForceRequest"]));
            }
            set {
                this["ForceRequest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\HtmlFiles\\CinemaIndex\\")]
        public string CinemasIndex {
            get {
                return ((string)(this["CinemasIndex"]));
            }
            set {
                this["CinemasIndex"] = value;
            }
        }
    }
}
