//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinevoTests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class CinevoScrapperTest : global::System.Configuration.ApplicationSettingsBase {
        
        private static CinevoScrapperTest defaultInstance = ((CinevoScrapperTest)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CinevoScrapperTest())));
        
        public static CinevoScrapperTest Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\CinevoTests\\FilesAreEqual\\Towns")]
        public string TownEqual {
            get {
                return ((string)(this["TownEqual"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\CinevoTests\\FilesAreEqual\\Towns\\Processed")]
        public string TownEqualProcessed {
            get {
                return ((string)(this["TownEqualProcessed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\CinevoTests\\FilesAreDiff\\Towns")]
        public string TownDiff {
            get {
                return ((string)(this["TownDiff"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\CinevoTests\\FilesAreDiff\\Towns\\Processed")]
        public string TownDiffProcessed {
            get {
                return ((string)(this["TownDiffProcessed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CleanDirectories {
            get {
                return ((bool)(this["CleanDirectories"]));
            }
        }
    }
}
