//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinevoTests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class CinevoScrapperTest : global::System.Configuration.ApplicationSettingsBase {
        
        private static CinevoScrapperTest defaultInstance = ((CinevoScrapperTest)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CinevoScrapperTest())));
        
        public static CinevoScrapperTest Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\CinevoTests\\FilesAreEqual")]
        public string EqualFilesDownloaded {
            get {
                return ((string)(this["EqualFilesDownloaded"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\CinevoTests\\FilesAreEqual\\Old")]
        public string EqualFilesOld {
            get {
                return ((string)(this["EqualFilesOld"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\CinevoTests\\FilesAreDiff")]
        public string DiffFilesDownloaded {
            get {
                return ((string)(this["DiffFilesDownloaded"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\CinevoTests\\FilesAreDiff\\Old")]
        public string DiffFilesOld {
            get {
                return ((string)(this["DiffFilesOld"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CleanDirectories {
            get {
                return ((bool)(this["CleanDirectories"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cartelera.elperiodico.com/cines/")]
        public string UrlTowns {
            get {
                return ((string)(this["UrlTowns"]));
            }
            set {
                this["UrlTowns"] = value;
            }
        }
    }
}
